# Generated by Django 4.0.3 on 2022-05-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0003_oddil_skaut_oddil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresaKlubovny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulice', models.CharField(max_length=100)),
                ('cislo_popisne', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='oddil',
            options={'verbose_name': 'Oddíl', 'verbose_name_plural': 'Oddíly'},
        ),
        migrations.AlterField(
            model_name='skaut',
            name='oddil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skauti', to='clenove.oddil', verbose_name='Oddíl'),
        ),
        migrations.AddField(
            model_name='oddil',
            name='klubovna',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clenove.adresaklubovny'),
        ),
    ]
