# Generated by Django 4.0.3 on 2022-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0004_adresaklubovny_alter_oddil_options_alter_skaut_oddil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('barva', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bobříci',
            },
        ),
        migrations.AlterModelOptions(
            name='adresaklubovny',
            options={'verbose_name_plural': 'Adresy kluboven'},
        ),
        migrations.AddField(
            model_name='skaut',
            name='bobrici',
            field=models.ManyToManyField(related_name='skauti', to='clenove.bobrik'),
        ),
    ]
